<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_error</name>
   <tag></tag>
   <elementGuidId>0ad675bd-7b0b-4b1e-b75a-6dcdcbd1100c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#E</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='E']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
