<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subtotal_price</name>
   <tag></tag>
   <elementGuidId>592c8f30-f3d4-4d26-bc10-2dcb4b39da72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.heading-sub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;spacing-prod-sub&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
