<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total_price</name>
   <tag></tag>
   <elementGuidId>78a5b3c4-3faf-4dbb-a5ce-df9053978dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.text-sub-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;spacing-prod-sub-last&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
