<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_to_wishlist_multiple</name>
   <tag></tag>
   <elementGuidId>114a3f95-8abc-4fb6-b45f-40352e550e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class=&quot;whilist&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class=&quot;whilist&quot;])[${i}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class=&quot;whilist&quot;])[${i}]</value>
   </webElementProperties>
</WebElementEntity>
