<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_qty_change_dropdown</name>
   <tag></tag>
   <elementGuidId>90fdd2b3-37a4-4128-9f78-b3cd86c32770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nice-select.qty.custom-select.numeric.prdQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@class=&quot;list&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
