<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PLP_Check_Stock_link</name>
   <tag></tag>
   <elementGuidId>8c25d0fd-e447-400c-be01-771b4858199d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cncanchor_444770631</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class=&quot;change-link&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Check stock')]</value>
   </webElementXpaths>
</WebElementEntity>
