<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Order_no_CNC</name>
   <tag></tag>
   <elementGuidId>2d6369f9-338e-4cef-bbe7-1312095e9feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@class=&quot;orderthanks-text&quot;]//strong)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
