<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_address_dropdown</name>
   <tag></tag>
   <elementGuidId>e49fba52-d873-4150-81f8-3ed90d223a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:changeAddressPCA(this, '', 'PCA');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>* Select your address from those listed below*Unit C4, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USUnit C3, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USUnit 2A, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USUnit C2, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USAutoglass, Unit B1, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USCatering &amp; Leisure Supplies Ltd, Unit B5, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USDouglas Stewart E D U Ltd, Unit B4, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USHooper Services Ltd, Unit A3, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USMountjoy, Unit C1, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USNational Plastics, Unit B2, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USOnline Cleaning UK, Unit A4, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USQuarr House, Unit C3, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USS C Vital Fitness, Unit B3, Mountbatten Business Park Jackson Close Portsmouth, PO6 1USSanctuary Vets, Unit A1, Mountbatten Business Park Jackson Close Portsmouth, PO6 1US</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='address']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shippingAddress']/span/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your Country'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your address manually'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/span/select</value>
   </webElementXpaths>
</WebElementEntity>
