<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pass_error</name>
   <tag></tag>
   <elementGuidId>4b42a228-5810-466a-ba37-d6a97b576d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;currentPasswordError&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=&quot;currentPasswordError&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
