<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_Paypal_radio</name>
   <tag></tag>
   <elementGuidId>16643b29-d1e6-46f6-8855-3be81167bbe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slot31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slot5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slot31']</value>
   </webElementXpaths>
</WebElementEntity>
