<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PLP_cart_popupclose</name>
   <tag></tag>
   <elementGuidId>0cc8e68f-da1d-4bfd-a102-c8ccfafdc539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close.top-6 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='addtocartsuccess']/div[2]/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/theme/ecp/assets/images/cross-icon-new.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;safari11 modal-open&quot;]/section[@class=&quot;container-fluid&quot;]/section[@class=&quot;container&quot;]/section[@class=&quot;row product-listing-col o3b-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;section3bo&quot;]/div[@class=&quot;rightcol3bo&quot;]/div[@class=&quot;product-section infinite-scroll&quot;]/div[@class=&quot;listing-view&quot;]/div[@id=&quot;addtocartsuccess&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/button[@class=&quot;close top-6&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addtocartsuccess']/div[2]/div/div/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/img</value>
   </webElementXpaths>
</WebElementEntity>
