<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basket_postcode_input</name>
   <tag></tag>
   <elementGuidId>56730b70-6d7a-45a4-bcd4-86a73b13ee8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#postcodedesk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postcodedesk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postcodedesk']</value>
   </webElementXpaths>
</WebElementEntity>
