<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_close_ST1</name>
   <tag></tag>
   <elementGuidId>e69af81f-5b17-4697-94d9-18668759a1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-image-type</name>
      <type>Main</type>
      <value>circle_new</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.bronto.com/popup/72a917e7-a59b-4f32-9dbf-74bd77408aed/a0bcd37a-5b01-4870-a2ac-06b56bfe60cb/close_circle_new.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Popup Close Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='popup-subcription-closes-icon-a0bcd37a-5b01-4870-a2ac-06b56bfe60cb-root']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.bronto.com/popup/72a917e7-a59b-4f32-9dbf-74bd77408aed/a0bcd37a-5b01-4870-a2ac-06b56bfe60cb/close_circle_new.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
