<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_close_LIVE</name>
   <tag></tag>
   <elementGuidId>f142991b-1e54-47cd-a9d7-e9eb68c49bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-image-type</name>
      <type>Main</type>
      <value>circle_fill</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.bronto.com/popup/cb603670-223a-4df0-8b56-c3aed547163d/cf19ea53-24fe-488f-ba42-3d4f5234f12d/close_circle_fill.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Popup Close Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='popup-subcription-closes-icon-cf19ea53-24fe-488f-ba42-3d4f5234f12d-root']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.bronto.com/popup/cb603670-223a-4df0-8b56-c3aed547163d/cf19ea53-24fe-488f-ba42-3d4f5234f12d/close_circle_fill.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
