<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_Column_Heading</name>
   <tag></tag>
   <elementGuidId>705e748e-800b-4a82-bd68-29ebe8d74b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[contains(text(),'Action')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
