<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout_Express_Delivery</name>
   <tag></tag>
   <elementGuidId>4656ea8e-45f0-442f-9185-eb9bbd45d51a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slotBDNDD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slotDHL24</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
